[server]
headless = true
port = 8501

[general]
page_title = "NichoSec V2"
page_icon = "ðŸ§ "

[theme]
base = "dark"
primaryColor = "#00ffff"

[client]
showSidebarNavigation = true

[runner]
magicEnabled = false

[global]
developmentMode = true

[app]
# This tells Streamlit which file to run on deployment
target = "src/ui/app.py"
